/**
 * Portable filesystem search engine.
 *
 * This is the single implementation of glob and grep used by Octo. It is kept
 * as a self-contained CommonJS program (only `node:fs` and `node:path`) so the
 * exact same code can be materialized and executed by every `Executor`:
 *
 * - Windows host  -> `node "<script>" "<base64 job>"` through PowerShell
 * - POSIX host    -> same command through `sh`
 * - docker/podman -> same command inside the container
 *
 * Keeping one implementation is deliberate: shelling out to `grep`/`findstr`
 * would give three different behaviors (PowerShell vs POSIX `sh` vs BusyBox),
 * and the sandbox image ships neither `rg` nor `fd`. Node is the only common
 * denominator across all of them.
 *
 * The program reads a base64 JSON job from `argv[2]`, writes a JSON envelope to
 * stdout, and always exits 0 — errors travel inside the envelope.
 *
 * IMPORTANT: authored with `String.raw`, so backslashes are literal. Do not
 * introduce backticks or `${` into the program text.
 */

/** Bumped whenever the program text changes; part of the materialized filename. */
export const SEARCH_ENGINE_VERSION = "7";

export const SEARCH_ENGINE_SOURCE = String.raw`"use strict";
// Generated by @octo/core-agent (search/engine-source.ts). Do not edit in place.
var fs = require("node:fs");
var path = require("node:path");

var DEFAULT_EXCLUDES = [".git", "node_modules", "dist", "build", "out", "coverage", ".cache", ".venv", "venv", "__pycache__", ".octo", ".next", ".turbo"];
var MAX_FILE_BYTES = 10 * 1024 * 1024;
var SNIFF_BYTES = 8192;
var MAX_SCAN_ENTRIES = 400000;
var DEFAULT_GLOB_LIMIT = 1000;
var DEFAULT_GREP_LIMIT = 250;
var MAX_DOCUMENT_CANDIDATES = 200;

function splitTopLevel(s) {
  var parts = [];
  var depth = 0;
  var cur = "";
  for (var i = 0; i < s.length; i++) {
    var c = s[i];
    if (c === "{") { depth++; cur += c; continue; }
    if (c === "}") { depth--; cur += c; continue; }
    if (c === "," && depth === 0) { parts.push(cur); cur = ""; continue; }
    cur += c;
  }
  parts.push(cur);
  return parts;
}

function globToRegExpSource(pattern) {
  var out = "";
  var i = 0;
  while (i < pattern.length) {
    var c = pattern[i];
    if (c === "*") {
      if (pattern[i + 1] === "*") {
        var j = i + 2;
        if (pattern[j] === "/") { out += "(?:[^/]*/)*"; i = j + 1; continue; }
        out += ".*";
        i = j;
        continue;
      }
      out += "[^/]*";
      i++;
      continue;
    }
    if (c === "?") { out += "[^/]"; i++; continue; }
    if (c === "[") {
      var k = i + 1;
      var negated = false;
      if (pattern[k] === "!" || pattern[k] === "^") { negated = true; k++; }
      var cls = "";
      while (k < pattern.length && pattern[k] !== "]") {
        if (pattern[k] === "\\") { cls += "\\" + (pattern[k + 1] || ""); k += 2; continue; }
        cls += pattern[k];
        k++;
      }
      if (k >= pattern.length) { out += "\\["; i++; continue; }
      out += "[" + (negated ? "^" : "") + cls + "]";
      i = k + 1;
      continue;
    }
    if (c === "{") {
      var depth = 1;
      var m = i + 1;
      var body = "";
      while (m < pattern.length) {
        if (pattern[m] === "{") depth++;
        else if (pattern[m] === "}") { depth--; if (depth === 0) break; }
        body += pattern[m];
        m++;
      }
      if (depth !== 0) { out += "\\{"; i++; continue; }
      var alts = splitTopLevel(body).map(globToRegExpSource);
      out += "(?:" + alts.join("|") + ")";
      i = m + 1;
      continue;
    }
    if ("\\^$.|+()".indexOf(c) !== -1) { out += "\\" + c; i++; continue; }
    out += c;
    i++;
  }
  return out;
}

// Builds a matcher over slash-normalized relative paths. A pattern without any
// "/" also matches the basename at any depth, which is how ripgrep and fd treat
// their --glob flag and what users expect from "*.ts".
function makeMatcher(pattern) {
  var normalized = String(pattern).replace(/\\/g, "/").replace(/^\.\//, "");
  var full = new RegExp("^" + globToRegExpSource(normalized) + "$");
  if (normalized.indexOf("/") !== -1) {
    return function (rel) { return full.test(rel); };
  }
  var base = new RegExp("^" + globToRegExpSource(normalized) + "$");
  return function (rel) {
    if (full.test(rel)) return true;
    var slash = rel.lastIndexOf("/");
    return base.test(slash === -1 ? rel : rel.slice(slash + 1));
  };
}

function toRelative(root, full) {
  var rel = path.relative(root, full);
  return rel.split(path.sep).join("/");
}

function walkFiles(root, extraExcludes, visit) {
  var excluded = {};
  var all = DEFAULT_EXCLUDES.concat(extraExcludes || []);
  for (var e = 0; e < all.length; e++) excluded[all[e]] = true;

  var scanned = 0;
  var stack = [root];
  var seenDirs = {};
  while (stack.length > 0) {
    var dir = stack.pop();
    var real;
    try { real = fs.realpathSync(dir); } catch (err) { continue; }
    if (seenDirs[real]) continue;
    seenDirs[real] = true;

    var entries;
    try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch (err) { continue; }
    for (var i = 0; i < entries.length; i++) {
      var ent = entries[i];
      if (ent.isSymbolicLink()) continue;
      var full = path.join(dir, ent.name);
      if (ent.isDirectory()) {
        if (excluded[ent.name]) continue;
        stack.push(full);
        continue;
      }
      if (!ent.isFile()) continue;
      scanned++;
      if (scanned > MAX_SCAN_ENTRIES) return { scanned: scanned, aborted: true };
      visit(full, toRelative(root, full));
    }
  }
  return { scanned: scanned, aborted: false };
}

function resolveRoot(cwd, p) {
  // Always normalize so reported paths look the same whether or not "path" was given.
  if (!p) return path.resolve(cwd);
  return path.isAbsolute(p) ? path.resolve(p) : path.resolve(cwd, p);
}

// A search covers the cwd plus any extra roots the executor declared (the
// session's attachments directory, which lives outside the artifacts cwd).
// An explicit "path" overrides all of that: when the caller names a directory,
// searching somewhere else as well would be surprising.
function resolveRoots(job) {
  if (job.path) return [resolveRoot(job.cwd, job.path)];
  var roots = [resolveRoot(job.cwd)];
  var extra = job.extraRoots || [];
  for (var i = 0; i < extra.length; i++) {
    var resolved = resolveRoot(job.cwd, extra[i]);
    if (roots.indexOf(resolved) !== -1) continue;
    // A root nested inside one already listed would double-count its files.
    var nested = false;
    for (var j = 0; j < roots.length; j++) {
      if (resolved.indexOf(roots[j] + path.sep) === 0 || roots[j].indexOf(resolved + path.sep) === 0) nested = true;
    }
    if (nested) continue;
    try { if (!fs.statSync(resolved).isDirectory()) continue; } catch (err) { continue; }
    roots.push(resolved);
  }
  return roots;
}

function runGlob(job) {
  var roots = resolveRoots(job);
  var matcher = makeMatcher(job.pattern);
  var matched = [];
  var scannedTotal = 0;
  for (var r = 0; r < roots.length; r++) {
    var walked = walkFiles(roots[r], job.exclude, function (full, rel) {
      if (matcher(rel)) matched.push(full);
    });
    scannedTotal += walked.scanned;
  }

  // Size comes from the same stat that mtime already needed, so carrying it back
  // is free. It is what lets a caller tell a 3-line CSV from a 300-page report
  // without opening either of them.
  var timed = matched.map(function (f) {
    var mtime = 0;
    var size = 0;
    try {
      var st = fs.statSync(f);
      mtime = st.mtimeMs;
      size = st.size;
    } catch (err) { mtime = 0; size = 0; }
    return { file: f, mtime: mtime, size: size };
  });
  timed.sort(function (a, b) {
    if (b.mtime !== a.mtime) return b.mtime - a.mtime;
    return a.file < b.file ? -1 : a.file > b.file ? 1 : 0;
  });

  var limit = job.limit && job.limit > 0 ? job.limit : DEFAULT_GLOB_LIMIT;
  var kept = timed.slice(0, limit);
  return {
    files: kept.map(function (x) { return x.file; }),
    entries: kept.map(function (x) { return { path: x.file, size: x.size, mtimeMs: x.mtime }; }),
    searchPath: roots.join(", "),
    roots: roots,
    limitReached: timed.length > limit,
    scanned: scannedTotal
  };
}

function looksBinary(buf) {
  var end = Math.min(buf.length, SNIFF_BYTES);
  for (var i = 0; i < end; i++) if (buf[i] === 0) return true;
  return false;
}

// Decodes a file to text, honoring a byte order mark. UTF-16 has to be handled
// explicitly: it is full of NUL bytes, so the binary sniff would otherwise reject
// it, and Notepad on Windows writes UTF-16LE whenever "Unicode" is selected.
function decodeText(buf) {
  if (buf.length >= 2 && buf[0] === 0xff && buf[1] === 0xfe) {
    return buf.slice(2).toString("utf16le");
  }
  if (buf.length >= 2 && buf[0] === 0xfe && buf[1] === 0xff) {
    // UTF-16BE: Node only decodes LE, so swap the byte pairs first.
    var swapped = Buffer.from(buf.slice(2));
    for (var i = 0; i + 1 < swapped.length; i += 2) {
      var tmp = swapped[i];
      swapped[i] = swapped[i + 1];
      swapped[i + 1] = tmp;
    }
    return swapped.toString("utf16le");
  }
  if (buf.length >= 3 && buf[0] === 0xef && buf[1] === 0xbb && buf[2] === 0xbf) {
    return buf.slice(3).toString("utf8");
  }
  if (looksBinary(buf)) return null;
  return buf.toString("utf8");
}

function readTextFile(file) {
  var stat;
  try { stat = fs.statSync(file); } catch (err) { return null; }
  if (!stat.isFile() || stat.size > MAX_FILE_BYTES) return null;
  var buf;
  try { buf = fs.readFileSync(file); } catch (err) { return null; }
  var text = decodeText(buf);
  if (text === null) return null;
  // Normalize CRLF up front: keeps reported lines clean and keeps the multiline
  // offset table consistent with the split-by-newline line array.
  return text.replace(/\r\n/g, "\n");
}

function collectFileMatches(job, file, reTest, reAll) {
  var content = readTextFile(file);
  if (content === null) return null;

  var lines = content.split("\n");
  var hitLines = [];

  if (job.multiline) {
    // Walk matches over the whole buffer and map each start offset to a line.
    var offsets = [0];
    for (var i = 0; i < lines.length; i++) offsets.push(offsets[i] + lines[i].length + 1);
    reAll.lastIndex = 0;
    var m;
    var guard = 0;
    while ((m = reAll.exec(content)) !== null) {
      guard++;
      if (guard > 100000) break;
      var lo = 0;
      var hi = offsets.length - 1;
      while (lo < hi) {
        var mid = (lo + hi + 1) >> 1;
        if (offsets[mid] <= m.index) lo = mid; else hi = mid - 1;
      }
      if (hitLines.length === 0 || hitLines[hitLines.length - 1] !== lo) hitLines.push(lo);
      if (m[0].length === 0) reAll.lastIndex++;
    }
  } else {
    for (var j = 0; j < lines.length; j++) {
      reTest.lastIndex = 0;
      if (reTest.test(lines[j])) hitLines.push(j);
    }
  }

  if (hitLines.length === 0) return null;
  return { lines: lines, hits: hitLines };
}

function extractOnlyMatching(text, reAll) {
  reAll.lastIndex = 0;
  var found = [];
  var m;
  var guard = 0;
  while ((m = reAll.exec(text)) !== null) {
    guard++;
    if (guard > 10000) break;
    found.push(m[0]);
    if (m[0].length === 0) reAll.lastIndex++;
  }
  return found;
}

function runGrep(job) {
  var roots = resolveRoots(job);
  var outputMode = job.outputMode || "content";

  var flags = "";
  if (job.ignoreCase) flags += "i";
  if (job.multiline) flags += "s";
  var reTest;
  var reAll;
  try {
    reTest = new RegExp(job.pattern, flags);
    reAll = new RegExp(job.pattern, flags + "g");
  } catch (err) {
    throw new Error("Invalid regular expression: " + (err && err.message ? err.message : String(err)));
  }

  // Only the primary root has to exist — an extra root is a convenience and is
  // dropped silently by resolveRoots when it is missing.
  var rootStats = [];
  for (var s = 0; s < roots.length; s++) {
    try { rootStats.push(fs.statSync(roots[s])); } catch (err) { throw new Error("Path not found: " + roots[s]); }
  }

  // Binary documents are collected during this same walk rather than searched:
  // their text has to be extracted by the caller, and walking the tree twice
  // would double the cost of every grep.
  var documentExtensions = job.documentExtensions || [];
  var wantDocuments = documentExtensions.length > 0;
  var documentCandidates = [];
  var documentCandidatesTruncated = false;

  function isDocumentPath(p) {
    var lower = p.toLowerCase();
    for (var i = 0; i < documentExtensions.length; i++) {
      if (lower.slice(-documentExtensions[i].length) === documentExtensions[i]) return true;
    }
    return false;
  }

  function addDocumentCandidate(p) {
    if (documentCandidates.length >= MAX_DOCUMENT_CANDIDATES) {
      documentCandidatesTruncated = true;
      return;
    }
    var size = 0;
    var mtimeMs = 0;
    try {
      var st = fs.statSync(p);
      size = st.size;
      mtimeMs = st.mtimeMs;
    } catch (err) {
      size = 0;
      mtimeMs = 0;
    }
    documentCandidates.push({ path: p, size: size, mtimeMs: mtimeMs });
  }

  var targets = [];
  var scanned = 0;
  var globMatcher = job.glob ? makeMatcher(job.glob) : null;
  for (var k = 0; k < roots.length; k++) {
    var thisRoot = roots[k];
    if (rootStats[k].isFile()) {
      if (wantDocuments && isDocumentPath(thisRoot)) {
        addDocumentCandidate(thisRoot);
      } else {
        targets.push(thisRoot);
      }
      scanned += 1;
      continue;
    }
    var walked = walkFiles(thisRoot, job.exclude, function (full, rel) {
      if (globMatcher && !globMatcher(rel)) return;
      if (wantDocuments && isDocumentPath(full)) {
        addDocumentCandidate(full);
        return;
      }
      targets.push(full);
    });
    scanned += walked.scanned;
  }
  targets.sort();
  documentCandidates.sort(function (a, b) { return a.path < b.path ? -1 : a.path > b.path ? 1 : 0; });

  var allLines = [];
  var files = [];
  var counts = [];
  var totalMatches = 0;
  var cappedFiles = 0;

  for (var t = 0; t < targets.length; t++) {
    var file = targets[t];
    var found = collectFileMatches(job, file, reTest, reAll);
    if (found === null) continue;

    totalMatches += found.hits.length;
    files.push(file);
    counts.push({ path: file, count: found.hits.length });

    if (outputMode !== "content") continue;

    var before = job.before && job.before > 0 ? job.before : 0;
    var after = job.after && job.after > 0 ? job.after : 0;
    // maxCount caps what is emitted per file, never what is counted: one verbose
    // file must not be able to hide every other file behind the head limit.
    var emit = job.maxCount && job.maxCount > 0 ? found.hits.slice(0, job.maxCount) : found.hits;
    var capped = emit.length < found.hits.length;
    var wanted = {};
    for (var h = 0; h < emit.length; h++) {
      var idx = emit[h];
      wanted[idx] = "match";
      for (var b = Math.max(0, idx - before); b < idx; b++) if (!wanted[b]) wanted[b] = "context";
      for (var a = idx + 1; a <= Math.min(found.lines.length - 1, idx + after); a++) if (!wanted[a]) wanted[a] = "context";
    }
    var ordered = Object.keys(wanted).map(Number).sort(function (x, y) { return x - y; });
    for (var o = 0; o < ordered.length; o++) {
      var lineIdx = ordered[o];
      var isMatch = wanted[lineIdx] === "match";
      var text = found.lines[lineIdx];
      if (job.onlyMatching && isMatch) {
        var pieces = extractOnlyMatching(text, reAll);
        for (var p = 0; p < pieces.length; p++) {
          allLines.push({ path: file, line: lineIdx + 1, text: pieces[p] });
        }
        continue;
      }
      var entry = { path: file, line: lineIdx + 1, text: text };
      if (!isMatch) entry.context = true;
      allLines.push(entry);
    }
    if (capped) cappedFiles++;
  }

  var matchedFiles = files.length;
  var offset = job.offset && job.offset > 0 ? job.offset : 0;
  var limit = job.headLimit === 0 ? 0 : (job.headLimit && job.headLimit > 0 ? job.headLimit : DEFAULT_GREP_LIMIT);

  function slice(arr) {
    var sliced = arr.slice(offset);
    if (limit === 0) return { items: sliced, cut: false };
    return { items: sliced.slice(0, limit), cut: sliced.length > limit };
  }

  var outLines = { items: [], cut: false };
  var outFiles = { items: [], cut: false };
  var outCounts = { items: [], cut: false };
  var limitReached = false;

  if (outputMode === "content") { outLines = slice(allLines); limitReached = outLines.cut; }
  else if (outputMode === "files_with_matches") { outFiles = slice(files); limitReached = outFiles.cut; }
  else {
    counts.sort(function (x, y) { return y.count - x.count; });
    outCounts = slice(counts);
    limitReached = outCounts.cut;
  }

  var grepResult = {
    outputMode: outputMode,
    lines: outLines.items,
    files: outFiles.items,
    counts: outCounts.items,
    searchPath: roots.join(", "),
    roots: roots,
    totalMatches: totalMatches,
    matchedFiles: matchedFiles,
    scanned: scanned,
    limitReached: limitReached,
    cappedFiles: cappedFiles
  };
  if (wantDocuments) {
    grepResult.documentCandidates = documentCandidates;
    grepResult.documentCandidatesTruncated = documentCandidatesTruncated;
  }
  return grepResult;
}

function main() {
  var arg = process.argv[2];
  if (!arg) {
    process.stdout.write(JSON.stringify({ ok: false, error: "missing job argument" }));
    return;
  }
  var job;
  try {
    job = JSON.parse(Buffer.from(arg, "base64").toString("utf8"));
  } catch (err) {
    process.stdout.write(JSON.stringify({ ok: false, error: "malformed job payload" }));
    return;
  }
  try {
    if (job.kind === "glob") {
      process.stdout.write(JSON.stringify({ ok: true, kind: "glob", result: runGlob(job) }));
    } else if (job.kind === "grep") {
      process.stdout.write(JSON.stringify({ ok: true, kind: "grep", result: runGrep(job) }));
    } else {
      process.stdout.write(JSON.stringify({ ok: false, error: "unknown job kind" }));
    }
  } catch (err) {
    process.stdout.write(JSON.stringify({ ok: false, error: err && err.message ? err.message : String(err) }));
  }
}

main();
`;
